In [1]:
import numpy as np
from scipy.integrate import solve_ivp

In [2]:
def load_state(file_name):
    """Utility function to load PSO Object

    :param file_name: .pkl file where PSO Object is saved
    :type file_name: str
    :return: pso object
    :rtype: PSO
    """
    import dill
    return dill.load(open(file_name, "rb"))

# Lorenz paramters and initial conditions.
sigma, beta, rho = 10, 2.667, 28
u0, v0, w0 = 0, 1, 1.05
tmax = 10



def lorenz(t, X, sigma, beta, rho):
    """The Lorenz equations."""
    u, v, w = X
    up = - sigma * (u - v)
    vp = rho * u - v - u * w
    wp = -beta * w + u * v
    return up, vp, wp


def solve_lorenz(lorenz, tmax, u0, v0, w0, sigma, beta, rho, n=1000):
    """Solving lorenz equation."""
    soln = solve_ivp(lorenz, (0, tmax), (u0, v0, w0), args=(sigma, beta, rho),
                     dense_output=True)
    t = np.linspace(0, tmax, n)
    x, y, z = soln.sol(t)
    return (x, y, z, t)


def create_data(tmax, u0, v0, w0, sigma, beta):
    (x, y, z, t) = solve_lorenz(lorenz, tmax, u0, v0, w0, sigma, beta, rho)
    return (x, y, z, t)


# creating data
data = create_data(tmax, u0, v0, w0, sigma, beta)

In [4]:
pso1 = load_state("lorenz_1.pkl") 
pso5 = load_state("lorenz_5.pkl")  
pso10 = load_state("lorenz_10.pkl") 
pso25 = load_state("lorenz_25.pkl") 
pso50 = load_state("lorenz_50.pkl") 
psoS = [pso1, pso5, pso10, pso25, pso50]

In [7]:
for pso in psoS:
    print(np.abs(pso.global_best_position-(sigma, beta, rho)), pso.global_best_value)

[3.73374903e-05 1.73711266e-05 5.70329431e-05] [0.00203832]
[2.19807556e-05 1.33589674e-05 2.63525502e-06] [0.00721235]
[0.91659403 0.36664861 0.98145392] [170.69575015]
[0.26354619 0.03562496 2.29595837] [994.98644906]
[15.23683871  1.16637518  5.59271271] [1823.61316596]
